export interface ShowcaseSection {
  id: string;
  label: string;
  description: string;
  components: readonly string[];
}

export const showcaseSections = [
  {
    id: "foundations",
    label: "Foundations",
    description: "Semantic color, typography, spacing, radius, and elevation tokens.",
    components: ["Color tokens", "Typography", "Spacing", "Elevation"],
  },
  {
    id: "icons",
    label: "Icons",
    description: "Tree-shakeable symbols with Lumen sizing, semantic tones, and decorative-by-default accessibility.",
    components: [
      "Icon",
      "AddIcon",
      "AlignCenterIcon",
      "AlignLeftIcon",
      "AlignRightIcon",
      "ArrowDownIcon",
      "ArrowLeftIcon",
      "ArrowRightIcon",
      "ArrowUpIcon",
      "BoldIcon",
      "CalendarIcon",
      "CheckIcon",
      "ChevronDownIcon",
      "ChevronLeftIcon",
      "ChevronRightIcon",
      "ChevronUpIcon",
      "CloseIcon",
      "CodeIcon",
      "CopyIcon",
      "DownloadIcon",
      "EditIcon",
      "EmailIcon",
      "ErrorIcon",
      "ErrorFilledIcon",
      "FavoriteIcon",
      "FilterIcon",
      "HelpIcon",
      "HomeIcon",
      "InformationIcon",
      "InformationFilledIcon",
      "ItalicIcon",
      "LaunchIcon",
      "LinkIcon",
      "ListBulletedIcon",
      "ListNumberedIcon",
      "MenuIcon",
      "MoreHorizontalIcon",
      "MoreVerticalIcon",
      "NotificationIcon",
      "QuoteIcon",
      "RedoIcon",
      "SaveIcon",
      "SearchIcon",
      "SettingsIcon",
      "StarIcon",
      "StrikethroughIcon",
      "SuccessIcon",
      "TextColorIcon",
      "TextFontIcon",
      "TrashIcon",
      "UnderlineIcon",
      "UndoIcon",
      "UploadIcon",
      "UserIcon",
      "ViewIcon",
      "ViewOffIcon",
      "WarningIcon",
      "WarningFilledIcon",
    ],
  },
  {
    id: "actions",
    label: "Actions",
    description: "Buttons and grouped controls for clear product actions.",
    components: [
      "Button",
      "ButtonGroup",
      "Toolbar",
      "ToolbarGroup",
      "ToolbarItem",
      "ToolbarLabel",
      "ToolbarSeparator",
      "ToolbarSpacer",
    ],
  },
  {
    id: "assistant",
    label: "Assistant",
    description: "A bottom-docked prompt composer for chat, assistant, and command surfaces.",
    components: [
      "PromptComposer",
      "PromptComposerField",
      "PromptComposerAttachments",
      "PromptComposerAttachment",
      "PromptComposerToolbar",
      "PromptComposerControls",
      "PromptComposerContextMeter",
      "PromptComposerActions",
      "PromptComposerSubmit",
    ],
  },
  {
    id: "forms",
    label: "Forms",
    description: "Labeled, described, validated, and keyboard-usable controls.",
    components: [
      "Input",
      "TextField",
      "Textarea",
      "Select",
      "Checkbox",
      "ChoiceField",
      "ChoiceFieldLabel",
      "ChoiceFieldDescription",
      "Radio",
      "Switch",
      "NumberInput",
      "SearchInput",
      "FileInput",
      "Slider",
      "Field",
      "FieldLabel",
      "FieldLabelMeta",
      "FieldLabelRow",
      "FieldSublabel",
      "FieldDescription",
      "FieldError",
      "Fieldset",
      "Legend",
      "CharacterCount",
      "PasswordField",
      "DateInput",
      "DateInputSegment",
      "ErrorSummary",
      "ErrorSummaryTitle",
      "ErrorSummaryList",
      "ErrorSummaryItem",
      "InputGroup",
      "InputGroupAddon",
    ],
  },
  {
    id: "feedback",
    label: "Feedback",
    description: "Status, progress, loading, and empty-state communication.",
    components: [
      "Alert",
      "Banner",
      "Badge",
      "Tag",
      "StatusIndicator",
      "Progress",
      "Spinner",
      "Skeleton",
      "EmptyState",
      "Separator",
    ],
  },
  {
    id: "data-display",
    label: "Data display",
    description: "Structured surfaces for metrics, records, and supporting details.",
    components: [
      "Card",
      "CardGroup",
      "Avatar",
      "Table",
      "DescriptionList",
      "List",
      "CodeBlock",
      "CodeToken",
      "Stat",
      "AvatarGroup",
      "AvatarGroupItem",
      "Callout",
      "SummaryList",
      "SummaryRow",
      "SummaryTerm",
      "SummaryDetails",
      "SummaryActions",
      "TaskList",
      "TaskListItem",
      "Truncate",
      "ClipboardCopy",
      "InlineEdit",
      "ResourceList",
      "ResourceListItem",
      "ResourceListContent",
      "ResourceListTitle",
      "ResourceListDescription",
      "ResourceListMetadata",
      "ResourceListMetadataItem",
      "ResourceListActions",
      "TableToolbar",
      "TableToolbarHeader",
      "TableToolbarTitle",
      "TableToolbarDescription",
      "TableToolbarFilters",
      "TableToolbarContent",
      "TableToolbarActions",
      "TableAppliedFilters",
      "TableFilterTag",
      "TableBatchActions",
      "TableSelectionCell",
      "TableSortableHead",
      "TableRowActions",
      "TableEmptyState",
      "TablePagination",
      "TableSortAnnouncement",
    ],
  },
  {
    id: "visualization",
    label: "Visualization",
    description: "Interactive relationship exploration with accessible filtering, selection, and inspection.",
    components: ["GraphExplorer", "GraphInspector"],
  },
  {
    id: "navigation",
    label: "Navigation",
    description: "Orientation and movement across product views and processes.",
    components: [
      "Breadcrumbs",
      "Pagination",
      "Steps",
      "Tabs",
      "SkipLink",
      "Link",
      "BackLink",
      "BackToTop",
      "JumpLinks",
      "JumpLink",
      "GlobalHeader",
      "GlobalHeaderInner",
      "GlobalHeaderBrand",
      "GlobalHeaderNav",
      "GlobalHeaderNavList",
      "GlobalHeaderNavItem",
      "GlobalHeaderNavLink",
      "GlobalHeaderActions",
      "PageHeader",
      "PageHeaderContent",
      "PageHeaderTitle",
      "PageHeaderDescription",
      "PageHeaderActions",
      "SideNav",
      "SideNavList",
      "SideNavNestedList",
      "SideNavItem",
      "SideNavLink",
      "SideNavGroup",
      "SideNavGroupLabel",
      "AppShell",
      "AppShellSidebar",
      "AppShellSidebarHeader",
      "AppShellSidebarContent",
      "AppShellSidebarFooter",
      "AppShellMain",
      "AppShellRail",
    ],
  },
  {
    id: "overlays",
    label: "Overlays",
    description: "Focus-managed dialogs and anchored contextual surfaces.",
    components: ["Dialog", "Drawer", "DropdownMenu", "Popover", "Tooltip"],
  },
  {
    id: "disclosure",
    label: "Disclosure",
    description: "Progressive disclosure using durable native semantics.",
    components: ["Disclosure", "Accordion"],
  },
  {
    id: "layout",
    label: "Layout",
    description: "Composable structure, readable content widths, semantic sections, and visually hidden content.",
    components: [
      "Container",
      "Stack",
      "Inline",
      "Grid",
      "VisuallyHidden",
      "PageContent",
      "PageSection",
      "PageSectionHeader",
      "PageSectionTitle",
      "PageSectionDescription",
      "PageSectionActions",
      "PageSectionContent",
      "SectionStack",
      "SectionBand",
      "SectionBandHeader",
      "SectionBandEyebrow",
      "SectionBandTitle",
      "SectionBandDescription",
      "SectionBandContent",
    ],
  },
] as const satisfies readonly ShowcaseSection[];

export const showcasedComponentCount = showcaseSections.reduce(
  (total, section) => total + section.components.length,
  0,
);

export function matchesSection(section: ShowcaseSection, query: string) {
  const normalizedQuery = query.trim().toLocaleLowerCase();

  if (!normalizedQuery) return true;

  return [section.label, section.description, ...section.components].some(
    (value) => value.toLocaleLowerCase().includes(normalizedQuery),
  );
}
